//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.15 at 04:25:43 PM CET 
//


package xlike_hr.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
/**
 * <p>Java class for item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="services" type="{}serviceList" minOccurs="0"/>
 *         &lt;element name="sentences" type="{}sentenceList" minOccurs="0"/>
 *         &lt;element name="nodes" type="{}nodeList" minOccurs="0"/>
 *         &lt;element name="frames" type="{}frameList" minOccurs="0"/>
 *         &lt;element name="conll" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "item", propOrder = {
    "services",
    "sentences",
    "nodes",
    "frames",
    "conll"
})
@XmlRootElement
public class Item {

    protected ServiceList services;
    protected SentenceList sentences;
    protected NodeList nodes;
    protected FrameList frames;
    protected String conll;
    
    //protected String nodesEnriched; TIN
    //protected String framesEnriched; TIN

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceList }
     *     
     */
    public ServiceList getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceList }
     *     
     */
    public void setServices(ServiceList value) {
        this.services = value;
    }

    /**
     * Gets the value of the sentences property.
     * 
     * @return
     *     possible object is
     *     {@link SentenceList }
     *     
     */
    public SentenceList getSentences() {
        return sentences;
    }

    /**
     * Sets the value of the sentences property.
     * 
     * @param value
     *     allowed object is
     *     {@link SentenceList }
     *     
     */
    public void setSentences(SentenceList value) {
        this.sentences = value;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link NodeList }
     *     
     */
    public NodeList getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeList }
     *     
     */
    public void setNodes(NodeList value) {
        this.nodes = value;
    }

    /**
     * Gets the value of the frames property.
     * 
     * @return
     *     possible object is
     *     {@link FrameList }
     *     
     */
    public FrameList getFrames() {
        return frames;
    }

    /**
     * Sets the value of the frames property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameList }
     *     
     */
    public void setFrames(FrameList value) {
        this.frames = value;
    }
    
    /*
    //TIN
    public void setFramesEnriched(String value) {
        this.framesEnriched = value;
    }
    
    //TIN
    public void setNodesEnriched(String value) {
        this.nodesEnriched = value;
    }
    
    //TIN
    public String getFramesEnriched() {
        return framesEnriched;
    }
    
    //TIN
    public String getNodesEnriched() {
        return nodesEnriched;
    }
    */

    /**
     * Gets the value of the conll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConll() {
        return conll;
    }

    /**
     * Sets the value of the conll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConll(String value) {
        this.conll = value;
    }

}
